Added paths for companies in server
thoth-tech/Internal-Systems pull request #42
Opened 2022-12-13 00:40 UTC by Arsh2607

2022-12-13 01:56 UTC, Tanish-22 requested changes
please update the version of your code

2022-12-14 04:07 UTC, Arsh2607 reviewed
Made the changes

2022-12-14 04:07 UTC, Arsh2607 commented
Done with the changes

2022-12-14 04:11 UTC, Tanish-22 approved these changes

2022-12-14 04:11 UTC, merged